# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name="Group's name")),
                ('title', models.CharField(max_length=20, verbose_name="Group's title")),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='band',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
