# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20160907_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name="User's username")),
                ('firstName', models.CharField(max_length=20, verbose_name="User's first name")),
                ('lastName', models.CharField(max_length=20, verbose_name="User's last name")),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name="User's email")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Group')),
            ],
        ),
    ]
